add support for ovs offload
Mmduh-483/antrea pull request #1
Opened 2020-04-30 07:42 UTC by Mmduh-483

2020-04-30 08:18 UTC, Mmduh-483 commented
@moshe010

2020-05-01 18:13 UTC, moshe010 requested changes
how the validate interface works for you?
https://github.com/Mmduh-483/antrea/blob/master/pkg/agent/cniserver/pod_configuration.go#L191

2020-05-01 18:13 UTC, moshe010 commented on go.mod
> +	github.com/Mellanox/sriovnet v0.0.0-20191103093832-a16b5a5bd280
please use tag v1.0.1

2020-05-01 18:13 UTC, moshe010 commented on go.mod
> +	github.com/satori/go.uuid v1.2.1-0.20181028125025-b2ce2384e17b // indirect
run go mod tidy will remove this

2020-05-01 18:16 UTC, moshe010 commented
also see if we can add unit-test to https://github.com/moshe010/antrea/blob/master/pkg/agent/cniserver/server_test.go

2020-07-16 05:11 UTC, closed without merging